# Project information
site_name: "Uganda EMR User Manual"
site_description: "A guide on how to use our products for Uganda EMR"
site_author: "METS Programme"
site_url: "https://github.com/METS-Programme/ugandaemr-technicalguide/"  
docs_dir: "."

# Repository
repo_name: "ugandaemr-usermanual"
repo_url: "https://github.com/METS-Programme/ugandaemr-usermanual"

# Copyright
copyright: "Copyright © 2021 METS Programme"

# Theme
theme:
  name: "material"
  palette:
    primary: "blue grey"
    accent: "indigo"
  language: "en"
  font:
    text: "Roboto"
    code: "Roboto Mono"
nav:
  - Home:
    - 'SUMMARY.md'
 
